let A;
const $ = id => document.getElementById(id);
async function login(){let r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('u').value,password:$('pw').value})});if(r.ok){loginBox(false);loadAdmin()}else $('err').textContent='Login failed. Check ADMIN_USER and ADMIN_PASSWORD in Render.'}
function loginBox(show){$('login').style.display=show?'block':'none';$('panel').style.display=show?'none':'block'}
async function loadAdmin(){let r=await fetch('/api/admin/all');if(!r.ok){loginBox(true);return}A=await r.json();renderAdmin()}
function renderAdmin(){$('settingsBox').innerHTML='<h3>Everything here can be edited without GitHub</h3>'+Object.keys(A.settings).map(k=>`<label>${k}<input id="s_${k}" value="${String(A.settings[k]??'').replace(/"/g,'&quot;')}"></label>`).join('')+'<button class="cta" onclick="saveSettings()">Save Store Settings</button>';
$('productsBox').innerHTML=A.products.map(p=>`<div class="dialog" style="display:block;margin:12px 0"><b>${p.name}</b> — ₹${p.price}<br>${p.category}<br><button onclick='editProduct(${JSON.stringify(p)})'>Edit</button> <button onclick="del('products',${p.id})">Delete</button></div>`).join('');
$('catsBox').innerHTML=A.categories.map(c=>`<div class="dialog" style="display:block;margin:12px 0"><b>${c.icon} ${c.name}</b> ${c.parent_id?'(sub-category)':'(main category)'}<br><button onclick='editCat(${JSON.stringify(c)})'>Edit</button> <button onclick="del('categories',${c.id})">Delete</button></div>`).join('');
$('adsBox').innerHTML=A.ads.map(a=>`<div class="dialog" style="display:block;margin:12px 0"><b>${a.title}</b> — ${a.headline}<br><button onclick='editAd(${JSON.stringify(a)})'>Edit</button> <button onclick="del('ads',${a.id})">Delete</button></div>`).join('')}
async function saveSettings(){let d={};Object.keys(A.settings).forEach(k=>d[k]=document.getElementById('s_'+k).value);await fetch('/api/admin/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});alert('Saved!')}
function form(title,fields,save){let html=`<div class="modal" id="edit"><div class="dialog"><h2>${title}</h2>`;fields.forEach(f=>html+=`<label>${f[0]}<input id="f_${f[1]}" value="${String(f[2]??'').replace(/"/g,'&quot;')}"></label>`);html+=`<button class="cta" onclick="${save}">Save</button> <button onclick="$('edit').remove()">Cancel</button></div></div>`;document.body.insertAdjacentHTML('beforeend',html)}
function newProduct(){form('Add Product',[['Name','name',''],['Price','price','0'],['Category','category','Toys'],['Image URL','image',''],['Description','description',''],['Stock','stock','0']], 'saveProduct()')}
function editProduct(p){form('Edit Product',[['Name','name',p.name],['Price','price',p.price],['Category','category',p.category],['Image URL','image',p.image],['Description','description',p.description],['Stock','stock',p.stock]], `saveProduct(${p.id})`)}
async function saveProduct(id){let d={id,name:f('name'),price:f('price'),category:f('category'),image:f('image'),description:f('description'),stock:f('stock'),active:true};await fetch('/api/admin/products',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});$('edit').remove();loadAdmin()}
function newCat(){form('Add Category',[['Name','name',''],['Parent category ID (blank = main)','parent_id',''],['Icon/emoji','icon','🧸'],['Sort order','sort_order','0']], 'saveCat()')}
function editCat(c){form('Edit Category',[['Name','name',c.name],['Parent category ID','parent_id',c.parent_id||''],['Icon/emoji','icon',c.icon],['Sort order','sort_order',c.sort_order]],`saveCat(${c.id})`)}
async function saveCat(id){let d={id,name:f('name'),parent_id:f('parent_id')||null,icon:f('icon'),sort_order:f('sort_order')};await fetch('/api/admin/categories',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});$('edit').remove();loadAdmin()}
function newAd(){form('Add Advertisement',[['Title','title','Banner'],['Headline','headline',''],['Text','text',''],['Button text','button','Shop Now'],['Image URL','image',''],['Order','sort_order','0']], 'saveAd()')}
function editAd(a){form('Edit Advertisement',[['Title','title',a.title],['Headline','headline',a.headline],['Text','text',a.text],['Button text','button',a.button],['Image URL','image',a.image],['Order','sort_order',a.sort_order]],`saveAd(${a.id})`)}
async function saveAd(id){let d={id,title:f('title'),headline:f('headline'),text:f('text'),button:f('button'),image:f('image'),sort_order:f('sort_order'),active:true};await fetch('/api/admin/ads',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});$('edit').remove();loadAdmin()}
async function del(type,id){if(confirm('Delete?')){await fetch('/api/admin/'+type,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});loadAdmin()}}
function f(x){return document.getElementById('f_'+x).value}async function logout(){await fetch('/api/admin/logout',{method:'POST'});loginBox(true)}loadAdmin().catch(()=>loginBox(true));
