let cats=[],products=[],ads=[],settings={};const $=id=>document.getElementById(id);
async function api(u,o){let r=await fetch(u,o);let j=await r.json();if(!r.ok)throw Error(j.error||"Error");return j}
async function init(){let s=await api("/api/admin/status");if(s.logged_in)showApp()}
async function login(){try{await api("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:$("au").value,password:$("ap").value})});showApp()}catch(e){$("loginMsg").textContent=e.message}}
async function logout(){await api("/api/admin/logout",{method:"POST"});location.reload()}
function showApp(){$("loginBox").classList.add("hidden");$("adminApp").classList.remove("hidden");refreshAll();tab("dashboard")}
async function refreshAll(){cats=(await api("/api/categories")).categories;products=(await api("/api/products")).products;ads=(await api("/api/ads")).ads;settings=(await api("/api/store")).settings||{};if(!$("adminApp").classList.contains("hidden"))renderCurrent()}
let current="dashboard";function tab(t){current=t;let names={dashboard:"Dashboard",products:"Products",categories:"Categories",ads:"Banners / Ads",orders:"Orders",settings:"Settings"};$("tabTitle").textContent=names[t];renderCurrent()}
function renderCurrent(){if(current==="dashboard")dashboard();if(current==="products")productTab();if(current==="categories")categoryTab();if(current==="ads")adTab();if(current==="orders")orderTab();if(current==="settings")settingsTab()}
function dashboard(){$("panel").innerHTML=`<div class="stats"><div class="stat">Products<b>${products.length}</b></div><div class="stat">Categories<b>${cats.length}</b></div><div class="stat">Active Ads<b>${ads.length}</b></div><div class="stat">Stock Units<b>${products.reduce((a,p)=>a+Number(p.stock||0),0)}</b></div></div><div class="form"><h2>Store control center</h2><p>Products, category trees, banners, orders and store settings are managed here. Category nesting has no fixed depth.</p></div>`}
function catOptions(selected=""){return cats.map(c=>`<option value="${c.id}" ${String(selected)===String(c.id)?"selected":""}>${esc(c.name)}</option>`).join("")}
function productTab(){$("panel").innerHTML=`<div class="form"><h2>Add Product</h2><div class="formgrid"><input id="pn" placeholder="Product name"><select id="pc"><option value="">Category</option>${catOptions()}</select><input id="pp" type="number" placeholder="Price"><input id="po" type="number" placeholder="Old price"><input id="ps" type="number" placeholder="Stock"><input id="pb" placeholder="Badge e.g. 20% OFF"><input id="pi" placeholder="Image URL or local SVG filename"><input id="pfile" type="file" accept="image/*" onchange="readImage('pfile','pi')"><textarea id="pd" placeholder="Description"></textarea></div><label><input id="pf" type="checkbox"> Featured</label><button onclick="addProduct()">Add Product</button></div><div class="tablebox"><table><tr><th>Product</th><th>Price</th><th>Stock</th><th>Category</th><th>Action</th></tr>${products.map(p=>`<tr><td>${esc(p.name)}</td><td>₹${p.price}</td><td>${p.stock}</td><td>${esc(p.category_name||"")}</td><td class="actions"><button class="edit" onclick="editProduct(${p.id})">Edit</button><button class="danger" onclick="delProduct(${p.id})">Delete</button></td></tr>`).join("")}</table></div>`}
function readImage(fileId,targetId){let f=$(fileId).files[0];if(!f)return;let r=new FileReader();r.onload=()=>$(targetId).value=r.result;r.readAsDataURL(f)}
async function addProduct(){await api("/api/admin/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("pn").value,category_id:$("pc").value||null,price:$("pp").value,old_price:$("po").value,stock:$("ps").value,badge:$("pb").value,image_url:$("pi").value,description:$("pd").value,featured:$("pf").checked})});await refreshAll()}
async function editProduct(id){
 let p=products.find(x=>x.id===id); if(!p)return;
 openEditor("Edit Product",[
 ["Name","name",p.name,"text"],["Description","description",p.description,"textarea"],["Price","price",p.price,"number"],["Old price","old_price",p.old_price,"number"],["Stock","stock",p.stock,"number"],["Badge","badge",p.badge||"","text"],["Image URL / uploaded image","image_url",p.image_url||"","text"]
 ],`<label>Category<select id="edit_category">${catOptions(p.category_id)}</select></label><label><input id="edit_featured" type="checkbox" ${p.featured?"checked":""}> Featured</label><input id="edit_file" type="file" accept="image/*" onchange="readImage('edit_file','edit_image_url')">`);
 $("edit_image_url").value=p.image_url||"";
 $("editorSave").onclick=async()=>{let d={};["name","description","price","old_price","stock","badge","image_url"].forEach(k=>d[k]=$("edit_"+k).value);d.category_id=$("edit_category").value||null;d.featured=$("edit_featured").checked;await api("/api/admin/products/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});closeEditor();await refreshAll()}
}
async function delProduct(id){if(confirm("Delete product?")){await api("/api/admin/products/"+id,{method:"DELETE"});await refreshAll()}}
function categoryTab(){$("panel").innerHTML=`<div class="form"><h2>Add Category / Subcategory / Sub-subcategory</h2><div class="formgrid"><input id="cn" placeholder="Category name"><select id="cp"><option value="">No parent (root)</option>${catOptions()}</select><input id="ci" placeholder="Icon / emoji" value="🧸"><input id="cs" type="number" placeholder="Sort order"></div><button onclick="addCat()">Add Category</button></div><div class="treeadmin">${catTree(null)}</div>`}
function catTree(parent,depth=0){return cats.filter(c=>(c.parent_id||null)===(parent||null)).map(c=>`<div style="padding-left:${depth*20}px"><b>${c.icon||"🧸"} ${esc(c.name)}</b> <button class="edit" onclick="editCat(${c.id})">Edit</button> <button class="danger" onclick="delCat(${c.id})">Delete</button>${catTree(c.id,depth+1)}</div>`).join("")}
async function addCat(){await api("/api/admin/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("cn").value,parent_id:$("cp").value||null,icon:$("ci").value,sort_order:$("cs").value||0})});await refreshAll()}
async function editCat(id){let c=cats.find(x=>x.id===id);openEditor("Edit Category",[["Name","name",c.name,"text"],["Icon","icon",c.icon||"🧸","text"],["Sort order","sort_order",c.sort_order||0,"number"]],`<label>Parent<select id="edit_parent"><option value="">Root</option>${catOptions(c.parent_id)}</select></label>`);$("editorSave").onclick=async()=>{await api("/api/admin/categories/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:$("edit_name").value,icon:$("edit_icon").value,parent_id:$("edit_parent").value||null,sort_order:$("edit_sort_order").value})});closeEditor();await refreshAll()}}
async function delCat(id){if(confirm("Delete this category and all nested subcategories?")){await api("/api/admin/categories/"+id,{method:"DELETE"});await refreshAll()}}
function adTab(){$("panel").innerHTML=`<div class="form"><h2>Add Banner / Advertisement</h2><div class="formgrid"><input id="at" placeholder="Title"><input id="as" placeholder="Subtitle"><input id="ai" placeholder="Image URL or local SVG filename"><input id="afile" type="file" accept="image/*" onchange="readImage('afile','ai')"><select id="apo"><option>home</option><option>after-products</option><option>between-products</option><option>footer</option></select><input id="ao" type="number" placeholder="Sort order"></div><button onclick="addAd()">Add Banner</button></div><div class="tablebox"><table><tr><th>Title</th><th>Position</th><th>Active</th><th>Action</th></tr>${ads.map(a=>`<tr><td>${esc(a.title)}</td><td>${a.position}</td><td>${a.active}</td><td><button class="edit" onclick="editAd(${a.id})">Edit</button><button class="danger" onclick="delAd(${a.id})">Delete</button></td></tr>`).join("")}</table></div>`}
async function addAd(){await api("/api/admin/ads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:$("at").value,subtitle:$("as").value,image_url:$("ai").value,position:$("apo").value,sort_order:$("ao").value||0,active:true})});await refreshAll()}
async function editAd(id){let a=ads.find(x=>x.id===id);openEditor("Edit Banner",[["Title","title",a.title,"text"],["Subtitle","subtitle",a.subtitle,"text"],["Image URL / uploaded image","image_url",a.image_url||"","text"],["Sort order","sort_order",a.sort_order||0,"number"]],`<input id="edit_file" type="file" accept="image/*" onchange="readImage('edit_file','edit_image_url')"><label>Position<select id="edit_position"><option>home</option><option>after-products</option><option>between-products</option><option>footer</option></select></label><label><input id="edit_active" type="checkbox" ${a.active?"checked":""}> Active</label>`);$("edit_position").value=a.position;$("editorSave").onclick=async()=>{await api("/api/admin/ads/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:$("edit_title").value,subtitle:$("edit_subtitle").value,image_url:$("edit_image_url").value,position:$("edit_position").value,sort_order:$("edit_sort_order").value,active:$("edit_active").checked})});closeEditor();await refreshAll()}}
async function delAd(id){if(confirm("Delete banner?")){await api("/api/admin/ads/"+id,{method:"DELETE"});await refreshAll()}}
async function orderTab(){let r=await api("/api/admin/orders");let os=r.orders||[];$("panel").innerHTML=`<div class="tablebox"><table><tr><th>Order</th><th>Customer</th><th>Phone</th><th>Total</th><th>Status</th></tr>${os.map(o=>`<tr><td>${esc(o.order_no)}</td><td>${esc(o.customer_name)}</td><td>${esc(o.phone)}</td><td>₹${o.total}</td><td>${esc(o.status)}</td></tr>`).join("")}</table></div>`}
function settingsTab(){$("panel").innerHTML=`<div class="form"><h2>Store Settings</h2><div class="formgrid">${field("Store Name","sn",settings.store_name)}${field("Tagline","st",settings.tagline)}${field("Phone","sp",settings.phone)}${field("Email","se",settings.email)}${field("Address","sa",settings.address)}${field("Logo URL / uploaded logo","sl",settings.logo_url||"logo.svg")}<input id="sfile" type="file" accept="image/*" onchange="readImage('sfile','sl')">${field("Facebook","sf",settings.facebook)}${field("Instagram","si",settings.instagram)}${field("YouTube","sy",settings.youtube)}${field("WhatsApp","sw",settings.whatsapp)}</div><textarea id="fa" placeholder="Footer about">${esc(settings.footer_about||"")}</textarea><textarea id="cr" placeholder="Copyright">${esc(settings.copyright||"")}</textarea><button onclick="saveSettings()">Save Settings</button></div>`}
function field(label,id,val){return `<label>${label}<input id="${id}" value="${esc(val||"")}"></label>`}
async function saveSettings(){let s={...settings,store_name:$("sn").value,tagline:$("st").value,phone:$("sp").value,email:$("se").value,address:$("sa").value,logo_url:$("sl").value,facebook:$("sf").value,instagram:$("si").value,youtube:$("sy").value,whatsapp:$("sw").value,footer_about:$("fa").value,copyright:$("cr").value};await api("/api/admin/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(s)});settings=s;alert("Settings saved");renderCurrent()}
function openEditor(title,fields,extra=""){let m=document.createElement("div");m.id="editor";m.className="modal";m.innerHTML=`<div class="modal-box"><button class="close" onclick="closeEditor()">×</button><h2>${title}</h2><div class="form">${fields.map(([lab,key,val,type])=>type==="textarea"?`<label>${lab}<textarea id="edit_${key}">${esc(val)}</textarea></label>`:`<label>${lab}<input id="edit_${key}" type="${type}" value="${esc(val)}"></label>`).join("")}${extra}<button id="editorSave" class="primary">Save</button></div></div>`;document.body.appendChild(m)}
function closeEditor(){$("editor")?.remove()}
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
init()
