let cats=[], products=[], ads=[], settings={}, cart=JSON.parse(localStorage.getItem("atoz-cart")||"[]");
const $=id=>document.getElementById(id);
async function api(u,o){let r=await fetch(u,o);let j=await r.json();if(!r.ok)throw Error(j.error||"Error");return j}
function saveCart(){localStorage.setItem("atoz-cart",JSON.stringify(cart));$("cartCount").textContent=cart.reduce((a,x)=>a+x.qty,0)}
function img(src,fallback="toy-car.svg"){return src||fallback}
async function boot(){
  try{settings=(await api("/api/store")).settings||{};cats=(await api("/api/categories")).categories||[];products=(await api("/api/products")).products||[];ads=(await api("/api/ads")).ads||[];render()}
  catch(e){document.body.insertAdjacentHTML("afterbegin",`<div style="padding:20px;background:#fee;color:#900">Database connection error: ${e.message}</div>`)}
}
function render(){
  const logoSrc=settings.logo_url||"logo.svg";
  document.querySelectorAll(".brand img").forEach(x=>x.src=logoSrc);
  $("topbar").innerHTML=`🔥 Flat 20% OFF on First Order &nbsp; | &nbsp; Free Delivery on orders above ₹499`;
  $("hero").innerHTML=`<div class="hero-inner"><div><div class="eyebrow">AtoZ Toys & Keychain</div><h1>Big Fun for <span>Little Ones</span></h1><p>Premium toys, gifts & keychains for every age.</p><button onclick="document.querySelector('#shop').scrollIntoView()">Shop Now</button></div><img src="hero-toys.svg"></div>`;
  $("homeAds").innerHTML=ads.filter(a=>a.position==="home").map(a=>adHTML(a)).join("");
  $("afterAds").innerHTML=ads.filter(a=>a.position==="after-products").map(a=>adHTML(a)).join("");
  const between=document.getElementById("betweenAds"); if(between) between.innerHTML=ads.filter(a=>a.position==="between-products").map(a=>adHTML(a)).join("");
  renderTree(); renderCats(); renderProducts(products); renderFooter(); populateSelect(); saveCart();
}
function adHTML(a){return `<div class="ad-card" style="background-image:linear-gradient(90deg,#0005,#0000),url('${esc(a.image_url)}')"><h3>${esc(a.title)}</h3><p>${esc(a.subtitle)}</p><button onclick="document.querySelector('#shop').scrollIntoView()">Shop Now</button></div>`}
function esc(s){return String(s??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll("'","&#39;")}
function children(id){return cats.filter(c=>(c.parent_id||null)===(id||null))}
function renderTree(){function node(parent,depth=0){return children(parent).map(c=>`<div class="catrow" style="padding-left:${12+depth*12}px"><span class="name" onclick="openCategory(${c.id})">${c.icon||"🧸"} ${esc(c.name)}</span>${children(c.id).length?`<button onclick="toggleSub(${c.id},event)">›</button>`:""}</div><div id="sub-${c.id}" class="subtree hidden">${node(c.id,depth+1)}</div>`).join("")}$("tree").innerHTML=node(null)}
function toggleSub(id,e){e.stopPropagation();$("sub-"+id)?.classList.toggle("hidden")}
function renderCats(){let roots=children(null);$("catChips").innerHTML=roots.slice(0,14).map(c=>`<div class="cat-chip" onclick="openCategory(${c.id})"><div class="icon">${c.icon||"🧸"}</div><b>${esc(c.name)}</b></div>`).join("")}
function descendants(id){let out=[id];children(id).forEach(c=>out.push(...descendants(c.id)));return out}
function openCategory(id){let c=cats.find(x=>x.id===id);if(!c)return;let ids=descendants(id);renderProducts(products.filter(p=>ids.includes(p.category_id)));$("productTitle").textContent=c.name;document.querySelector("#shop").scrollIntoView({behavior:"smooth"})}
function showAllCategories(){renderProducts(products);$("productTitle").textContent="Best Selling Toys";document.querySelector("#shop").scrollIntoView({behavior:"smooth"})}
function renderProducts(list){$("products").innerHTML=list.length?list.map(p=>`<article class="product" onclick="openProduct(${p.id})"><span class="badge">${esc(p.badge||"")}</span><img src="${esc(img(p.image_url))}" onerror="this.src='toy-car.svg'"><h3>${esc(p.name)}</h3><div class="stars">★★★★★</div><div class="price">₹${Number(p.price).toLocaleString("en-IN")} <span class="old">₹${Number(p.old_price||0).toLocaleString("en-IN")}</span></div><button class="add" onclick="event.stopPropagation();addCart(${p.id})">Add to Cart</button></article>`).join(""):`<div style="padding:30px">No products found.</div>`}
async function loadProducts(){products=(await api("/api/products")).products;renderProducts(products)}
function doSearch(){let q=$("searchInput").value.trim().toLowerCase();renderProducts(products.filter(p=>(p.name+" "+p.description).toLowerCase().includes(q)));$("productTitle").textContent=q?`Search: ${q}`:"Best Selling Toys";document.querySelector("#shop").scrollIntoView({behavior:"smooth"})}
function populateSelect(){$("catSelect").innerHTML='<option value="">All Categories</option>'+cats.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");$("catSelect").onchange=()=>{const v=$("catSelect").value;v?openCategory(+v):showAllCategories()}}
function addCart(id){let p=products.find(x=>x.id===id);if(!p)return;let x=cart.find(x=>x.id===id);x?x.qty++:cart.push({id:p.id,name:p.name,price:Number(p.price),image:p.image_url,qty:1});saveCart();openCart()}
async function openProduct(id){let p=(await api("/api/products/"+id)).product;openModal(`<img src="${esc(img(p.image_url))}" style="width:180px;float:left;margin:0 20px 15px 0;background:#f8f6ff;border-radius:14px"><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><h2>₹${Number(p.price).toLocaleString("en-IN")}</h2><p>Stock: ${p.stock}</p><button class="primary" onclick="addCart(${p.id});closeModal()">Add to Cart</button><div style="clear:both"></div>`)}
function openCart(){let total=cart.reduce((a,x)=>a+x.price*x.qty,0);openModal(`<h2>Your Cart</h2>${cart.length?cart.map(x=>`<div class="cartline"><img src="${esc(img(x.image))}"><div><b>${esc(x.name)}</b><div>₹${x.price} × ${x.qty}</div><button onclick="changeQty(${x.id},-1)">−</button> <button onclick="changeQty(${x.id},1)">+</button></div></div>`).join("")+`<h2>Total: ₹${total.toLocaleString("en-IN")}</h2><button class="primary" onclick="checkout()">Proceed to Checkout</button>`:"<p>Your cart is empty.</p>"}`)}
function changeQty(id,n){let x=cart.find(x=>x.id===id);if(!x)return;x.qty+=n;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);saveCart();openCart()}
function checkout(){if(!cart.length)return;openModal(`<h2>Checkout</h2><div class="form"><input id="coName" placeholder="Full name"><input id="coPhone" placeholder="Phone number"><textarea id="coAddress" placeholder="Full delivery address"></textarea><button class="primary" onclick="placeOrder()">Place Order</button></div>`)}
async function placeOrder(){let total=cart.reduce((a,x)=>a+x.price*x.qty,0);try{let r=await api("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer_name:$("coName").value,phone:$("coPhone").value,address:$("coAddress").value,items:cart,total})});cart=[];saveCart();openModal(`<h2>Order placed 🎉</h2><p>Your order number is <b>${r.order.order_no}</b></p><p>Use Track Order to check status.</p>`)}catch(e){alert(e.message)}}
function openTrack(){openModal(`<h2>Track Order</h2><input id="trackNo" placeholder="Enter order number"><button class="primary" onclick="trackOrder()">Track</button><div id="trackResult"></div>`)}
async function trackOrder(){try{let r=await api("/api/orders/"+encodeURIComponent($("trackNo").value));$("trackResult").innerHTML=`<p><b>${r.order.order_no}</b><br>Status: ${r.order.status}</p>`}catch(e){$("trackResult").textContent=e.message}}
function openAccount(){
  const n=localStorage.getItem("atoz-name")||"";
  openModal(`<h2>My Account</h2><div class="form"><input id="accName" placeholder="Your name" value="${esc(n)}"><input id="accEmail" placeholder="Email"><button class="primary" onclick="localStorage.setItem('atoz-name',$('accName').value);openModal('<h2>Profile saved ✓</h2><p>Your local customer profile is saved on this device.</p>')">Save Profile</button></div><p>Orders can be tracked using your order number.</p>`)
}
function openModal(html){$("modalBody").innerHTML=html;$("modal").classList.remove("hidden")}
function closeModal(){$("modal").classList.add("hidden")}
function toggleSide(){$("sideCats").style.display=$("sideCats").style.display==="none"?"block":""}
function goHome(){location.href="/"}
function openInfo(title,html){openModal(`<h2>${esc(title)}</h2><div class="info-copy">${html}</div>`)}
function subscribe(){const e=$("newsletterEmail")?.value.trim();if(!e)return alert("Please enter your email");openInfo("Subscribed ✓","Thanks! "+esc(e)+" has been added to our newsletter list on this device.")}
function renderFooter(){$("footer").innerHTML=`<div class="footer-grid"><div><img src="logo-light.svg" style="width:170px"><p>${esc(settings.footer_about||"Your one-stop shop for toys, gifts and keychains.")}</p><p>📞 ${esc(settings.phone||"")}<br>✉️ ${esc(settings.email||"")}<br>📍 ${esc(settings.address||"")}</p><div class="newsletter"><input id="newsletterEmail" type="email" placeholder="Your email"><button onclick="subscribe()">Subscribe</button></div></div><div><h3>Customer Service</h3><a onclick="openInfo('Contact Us','📞 '+esc(settings.phone||'')+'<br>✉️ '+esc(settings.email||'')+'<br>📍 '+esc(settings.address||''))">Contact Us</a><a onclick="openInfo('About Us','AtoZ Toys & Keychain — a colorful destination for toys, gifts and keychains.')">About Us</a><a onclick="openTrack()">Track Order</a><a onclick="openInfo('Shipping Policy','Free delivery on qualifying orders. Delivery times vary by location.')">Shipping Policy</a><a onclick="openInfo('Returns & Refund','Contact us with your order number for return and refund assistance.')">Returns & Refund</a><a onclick="openInfo('FAQ / Help','For help with orders, products or delivery, contact our store team.')">FAQ / Help</a></div><div><h3>My Account</h3><a onclick="openInfo('My Orders','Use Track Order with your order number to check an order.')">My Orders</a><a onclick="openInfo('Wishlist','Wishlist is ready for future product saving.')">Wishlist</a><a onclick="openCart()">My Cart</a><a onclick="openAccount()">Login / Register</a><a onclick="openAccount()">Account Settings</a></div><div><h3>Information</h3><a onclick="openInfo('About Us','AtoZ Toys & Keychain — toys, gifts and keychains for every little adventure.')">About Us</a><a onclick="openInfo('Privacy Policy','We use order and profile information only to provide store services.')">Privacy Policy</a><a onclick="openInfo('Terms & Conditions','Product availability, pricing and delivery are subject to confirmation.')">Terms & Conditions</a><a onclick="openInfo('Cancellation Policy','Contact the store as soon as possible if you need to cancel an order.')">Cancellation Policy</a><a onclick="openInfo('Cookie Policy','This edition uses browser storage for cart and lightweight profile features.')">Cookie Policy</a><a onclick="openInfo('Sitemap','Home · Shop · Categories · Offers · Track Order · Account')">Sitemap</a></div><div><h3>Popular Categories</h3>${children(null).slice(0,7).map(c=>`<a onclick="openCategory(${c.id})">${esc(c.name)}</a>`).join("")}</div></div><div class="footer-ad">${ads.filter(a=>a.position==="footer").map(a=>adHTML(a)).join("")}</div><div class="copyright"><span>${esc(settings.copyright||"© 2026 AtoZ Toys. All Rights Reserved.")}</span><span>Made with ♥ for little customers · English · हिन्दी</span></div>`}
function closeOnBackdrop(e){if(e.target.id==="modal")closeModal()}$("modal").addEventListener("click",closeOnBackdrop);boot()
