let DATA={products:[],categories:[],ads:[],settings:{}};let cart=[];
async function load(){const r=await fetch('/api/store');DATA=await r.json();render();}
function render(){const s=DATA.settings;document.title=s.store_name||'AtoZ Toys';logo.textContent=s.logo||'🧸';storeName.textContent=s.store_name;fName.textContent=s.store_name;fAbout.textContent=s.footer_about;copyright.textContent=s.copyright;
nav.innerHTML=DATA.categories.filter(c=>!c.parent_id).map(c=>`<button onclick="filterCat('${esc(c.name)}')">${c.icon} ${esc(c.name)}</button>`).join('');
const hero=DATA.ads[0]||{};document.getElementById('hero').innerHTML=`<div><h1>${esc(hero.headline||s.tagline)}</h1><p>${esc(hero.text||s.footer_about)}</p><button class="cta" onclick="showAll()">${esc(hero.button||'Shop Now')} ✨</button></div>`;
categories.innerHTML=DATA.categories.filter(c=>!c.parent_id).map(c=>`<div class="cat" onclick="filterCat('${esc(c.name)}')"><div class="ico">${c.icon}</div><b>${esc(c.name)}</b><small>${DATA.categories.filter(x=>x.parent_id===c.id).length} collections</small></div>`).join('');
showProducts(DATA.products.slice(0,8));midAds.innerHTML=DATA.ads.slice(1).map(a=>`<div class="ad" style="${a.image?`background-image:linear-gradient(#0006,#0006),url('${a.image}');background-size:cover;background-position:center`:''}"><h2>${esc(a.headline)}</h2><p>${esc(a.text)}</p><button class="cta" onclick="showAll()">${esc(a.button)}</button></div>`).join('');
fInsta.href=s.instagram||'#';fFb.href=s.facebook||'#';fYt.href=s.youtube||'#';}
function showProducts(list){products.innerHTML=list.map(p=>`<article class="product"><img src="${p.image||'https://placehold.co/600x400?text=Toy'}" alt=""><div class="info"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><div class="price">₹${Number(p.price).toLocaleString('en-IN')}</div><button onclick="detail(${p.id})">View Product</button></div></article>`).join('')||'<p>No products found.</p>'}
function showAll(){showProducts(DATA.products)}
function filterCat(name){let children=DATA.categories.filter(c=>c.name===name||c.parent_id===DATA.categories.find(x=>x.name===name)?.id).map(c=>c.name);children.push(name);showProducts(DATA.products.filter(p=>children.includes(p.category)));window.scrollTo({top:document.getElementById('products').offsetTop-80,behavior:'smooth'});}
function detail(id){const p=DATA.products.find(x=>x.id===id);modal.classList.remove('hidden');modal.innerHTML=`<div class="dialog"><button onclick="closeModal()">✕</button><img src="${p.image}" alt=""><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><h2>₹${Number(p.price).toLocaleString('en-IN')}</h2><button class="cta" onclick="addCart(${p.id})">Add to Cart 🛒</button></div>`}
function addCart(id){cart.push(id);cartCount.textContent=cart.length;closeModal()}
function openCart(){modal.classList.remove('hidden');let items=cart.map(id=>DATA.products.find(p=>p.id===id));modal.innerHTML=`<div class="dialog"><button onclick="closeModal()">✕</button><h2>Your Cart (${items.length})</h2>${items.map(p=>`<p><b>${esc(p.name)}</b> — ₹${p.price}</p>`).join('')||'<p>Your cart is empty.</p>'}<button class="cta" onclick="alert('Checkout is ready for your payment gateway integration.')">Proceed to Checkout</button></div>`}
function closeModal(){modal.classList.add('hidden')}search.oninput=e=>{let q=e.target.value.toLowerCase();showProducts(DATA.products.filter(p=>(p.name+' '+p.category+' '+p.description).toLowerCase().includes(q)))};function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}load();
