services:
  - type: web
    name: atoztoys-v12
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
